version: '3'

services:
  selenium:
    build:
      context: .
      dockerfile: docker-files/Dockerfile-selenium
    container_name: selenium
    networks:
      - network_easy
    tty: true
    restart: always
    ports:
      - "4444:4444"

networks:
  network_easy:
    driver: bridge

volumes:
  data-volume:
    driver: local
